[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
shadow_lend = "ShdwLend111111111111111111111111111111111111"

[programs.testnet]
shadow_lend = "ShdwLend111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
